'use strict';function l(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:l(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ba(this);function t(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var k=a[d];if(!(k in c))break a;c=c[k]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}var w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var ca={a:!0},da={};try{da.__proto__=ca;x=da.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ea=w;
function y(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ea)ea(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype}function z(){this.m=!1;this.j=null;this.h=void 0;this.g=1;this.s=this.i=0;this.l=null}function A(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}z.prototype.o=function(a){this.h=a};
function C(a,b){a.l={exception:b,H:!0};a.g=a.i||a.s}z.prototype.return=function(a){this.l={return:a};this.g=this.s};function D(a,b,c){a.g=c;return{value:b}}function E(a){a.i=0;var b=a.l.exception;a.l=null;return b}function fa(a){this.g=new z;this.h=a}function ha(a,b){A(a.g);var c=a.g.j;if(c)return F(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return G(a)}
function F(a,b,c,d){try{var k=b.call(a.g.j,c);if(!(k instanceof Object))throw new TypeError("Iterator result "+k+" is not an object");if(!k.done)return a.g.m=!1,k;var m=k.value}catch(f){return a.g.j=null,C(a.g,f),G(a)}a.g.j=null;d.call(a.g,m);return G(a)}function G(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,C(a.g,c)}a.g.m=!1;if(a.g.l){b=a.g.l;a.g.l=null;if(b.H)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ia(a){this.next=function(b){A(a.g);a.g.j?b=F(a,a.g.j.next,b,a.g.o):(a.g.o(b),b=G(a));return b};this.throw=function(b){A(a.g);a.g.j?b=F(a,a.g.j["throw"],b,a.g.o):(C(a.g,b),b=G(a));return b};this.return=function(b){return ha(a,b)};this[Symbol.iterator]=function(){return this}}function ja(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,k){function m(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(m,k)}m(a.next())})}
function H(a){return ja(new ia(new fa(a)))}t("Symbol",function(a){function b(m){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(m||"")+"_"+k++,m)}function c(m,f){this.g=m;q(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",k=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ka(l(this))}})}return a});function ka(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
t("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.o=!1;var e=this.j();try{f(e.resolve,e.reject)}catch(g){e.reject(g)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(e){e(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var e=this;this.i(function(){e.l()})}this.g.push(f)};var k=r.setTimeout;c.prototype.i=function(f){k(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var e=0;e<f.length;++e){var g=
f[e];f[e]=null;try{g()}catch(h){this.j(h)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(h){return function(n){g||(g=!0,h.call(e,n))}}var e=this,g=!1;return{resolve:f(this.A),reject:f(this.l)}};b.prototype.A=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.C(f);else{a:switch(typeof f){case "object":var e=null!=f;break a;case "function":e=!0;break a;default:e=!1}e?this.v(f):this.m(f)}};
b.prototype.v=function(f){var e=void 0;try{e=f.then}catch(g){this.l(g);return}"function"==typeof e?this.G(e,f):this.m(f)};b.prototype.l=function(f){this.s(2,f)};b.prototype.m=function(f){this.s(1,f)};b.prototype.s=function(f,e){if(0!=this.h)throw Error("Cannot settle("+f+", "+e+"): Promise already settled in state"+this.h);this.h=f;this.i=e;2===this.h&&this.B();this.D()};b.prototype.B=function(){var f=this;k(function(){if(f.F()){var e=r.console;"undefined"!==typeof e&&e.error(f.i)}},1)};b.prototype.F=
function(){if(this.o)return!1;var f=r.CustomEvent,e=r.Event,g=r.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof e?f=new e("unhandledrejection",{cancelable:!0}):(f=r.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return g(f)};b.prototype.D=function(){if(null!=this.g){for(var f=0;f<this.g.length;++f)m.h(this.g[f]);this.g=null}};var m=new c;b.prototype.C=
function(f){var e=this.j();f.u(e.resolve,e.reject)};b.prototype.G=function(f,e){var g=this.j();try{f.call(e,g.resolve,g.reject)}catch(h){g.reject(h)}};b.prototype.then=function(f,e){function g(v,B){return"function"==typeof v?function(T){try{h(v(T))}catch(U){n(U)}}:B}var h,n,u=new b(function(v,B){h=v;n=B});this.u(g(f,h),g(e,n));return u};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.u=function(f,e){function g(){switch(h.h){case 1:f(h.i);break;case 2:e(h.i);break;default:throw Error("Unexpected state: "+
h.h);}}var h=this;null==this.g?m.h(g):this.g.push(g);this.o=!0};b.resolve=d;b.reject=function(f){return new b(function(e,g){g(f)})};b.race=function(f){return new b(function(e,g){for(var h=p(f),n=h.next();!n.done;n=h.next())d(n.value).u(e,g)})};b.all=function(f){var e=p(f),g=e.next();return g.done?d([]):new b(function(h,n){function u(T){return function(U){v[T]=U;B--;0==B&&h(v)}}var v=[],B=0;do v.push(void 0),B++,d(g.value).u(u(v.length-1),n),g=e.next();while(!g.done)})};return b});
function I(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(g){this.g=(e+=Math.random()+1).toString();if(g){g=p(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(g){var h=typeof g;return"object"===h&&null!==g||"function"===h}function k(g){if(!I(g,f)){var h=new c;q(g,f,{value:h})}}function m(g){var h=Object[g];h&&(Object[g]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&k(n);return h(n)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),
n=new a([[g,2],[h,3]]);if(2!=n.get(g)||3!=n.get(h))return!1;n.delete(g);n.set(h,4);return!n.has(g)&&4==n.get(h)}catch(u){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();m("freeze");m("preventExtensions");m("seal");var e=0;b.prototype.set=function(g,h){if(!d(g))throw Error("Invalid WeakMap key");k(g);if(!I(g,f))throw Error("WeakMap key fail: "+g);g[f][this.g]=h;return this};b.prototype.get=function(g){return d(g)&&I(g,f)?g[f][this.g]:void 0};b.prototype.has=function(g){return d(g)&&I(g,
f)&&I(g[f],this.g)};b.prototype.delete=function(g){return d(g)&&I(g,f)&&I(g[f],this.g)?delete g[f][this.g]:!1};return b});
t("Map",function(a){function b(){var e={};return e.previous=e.next=e.head=e}function c(e,g){var h=e[1];return ka(function(){if(h){for(;h.head!=e[1];)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:g(h)};h=null}return{done:!0,value:void 0}})}function d(e,g){var h=g&&typeof g;"object"==h||"function"==h?m.has(g)?h=m.get(g):(h=""+ ++f,m.set(g,h)):h="p_"+g;var n=e[0][h];if(n&&I(e[0],h))for(e=0;e<n.length;e++){var u=n[e];if(g!==g&&u.key!==u.key||g===u.key)return{id:h,list:n,index:e,entry:u}}return{id:h,
list:n,index:-1,entry:void 0}}function k(e){this[0]={};this[1]=b();this.size=0;if(e){e=p(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),g=new a(p([[e,"s"]]));if("s"!=g.get(e)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var h=g.entries(),n=h.next();if(n.done||n.value[0]!=e||"s"!=n.value[1])return!1;n=h.next();return n.done||4!=
n.value[0].x||"t"!=n.value[1]||!h.next().done?!1:!0}catch(u){return!1}}())return a;var m=new WeakMap;k.prototype.set=function(e,g){e=0===e?0:e;var h=d(this,e);h.list||(h.list=this[0][h.id]=[]);h.entry?h.entry.value=g:(h.entry={next:this[1],previous:this[1].previous,head:this[1],key:e,value:g},h.list.push(h.entry),this[1].previous.next=h.entry,this[1].previous=h.entry,this.size++);return this};k.prototype.delete=function(e){e=d(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||
delete this[0][e.id],e.entry.previous.next=e.entry.next,e.entry.next.previous=e.entry.previous,e.entry.head=null,this.size--,!0):!1};k.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};k.prototype.has=function(e){return!!d(this,e).entry};k.prototype.get=function(e){return(e=d(this,e).entry)&&e.value};k.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};k.prototype.keys=function(){return c(this,function(e){return e.key})};k.prototype.values=
function(){return c(this,function(e){return e.value})};k.prototype.forEach=function(e,g){for(var h=this.entries(),n;!(n=h.next()).done;)n=n.value,e.call(g,n[1],n[0],this)};k.prototype[Symbol.iterator]=k.prototype.entries;var f=0;return k});
t("Set",function(a){function b(c){this.g=new Map;if(c){c=p(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(p([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var k=d.entries(),m=k.next();if(m.done||m.value[0]!=c||m.value[1]!=c)return!1;m=k.next();return m.done||m.value[0]==c||4!=m.value[0].x||
m.value[1]!=m.value[0]?!1:k.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var k=this;this.g.forEach(function(m){return c.call(d,m,m,k)})};return b});t("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(e){return e};var k=[],m="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof m){b=m.call(b);for(var f=0;!(m=b.next()).done;)k.push(c.call(d,m.value,f++))}else for(m=b.length,f=0;f<m;f++)k.push(c.call(d,b[f],f));return k}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var la=this||self;function J(a){this.locked=a}function K(a){this.errorType=a}K.prototype.toString=function(){return this.errorType};function ma(a){this.errorType="This Chrome API is not available";this.call=a}y(ma,K);function L(a,b){this.errorType="Error executing Chrome API";this.call=a;this.message=b||""}y(L,K);L.prototype.toString=function(){return this.call+" returned '"+this.message+"'"};function na(){this.errorType="Tab is not locked"}y(na,K);
function oa(){this.errorType="Devtools cannot be open when locking"}y(oa,K);function M(){this.errorType="Unknown command"}y(M,K);function N(a){this.errorType="Unknown Error";this.exception=pa(a)}y(N,K);N.prototype.toString=function(){return K.prototype.toString.call(this)+(this.exception.message?". Details: '"+this.exception.message+"'":"")};function qa(){this.errorType="Window is not locked"}y(qa,K);function pa(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=a[c]});return b};function O(a){for(var b=void 0,c=la,d=p(a.split(".")),k=d.next();!k.done;k=d.next())if(k=k.value,b=c,c=c[k],void 0==c)return function(){return Promise.reject(new ma(a))};return function(m){var f=Array.prototype.slice.call(arguments);return new Promise(function(e,g){f.push(function(h){if(chrome.runtime.lastError)g(new L(a,chrome.runtime.lastError.message));else switch(arguments.length){case 0:e(void 0);break;case 1:e(arguments[0]);break;default:e(Array.prototype.slice.call(arguments))}});c.apply(b,
f)})}};var P=new function(){this.o=O("chrome.tabs.discard");this.A=O("chrome.tabs.query");this.v=O("chrome.tabs.move");this.F=O("chrome.tabs.group");this.B=O("chrome.tabs.reload");this.C=O("chrome.tabs.update");this.createWindow=O("chrome.windows.create");this.h=O("chrome.windows.getCurrent");this.D=O("chrome.windows.get");this.l=O("chrome.windows.update");this.s=O("chrome.management.getAll");this.i=O("chrome.management.setEnabled");O("chrome.storage.local.clear");this.m=O("chrome.storage.local.get");this.g=
O("chrome.storage.local.remove");this.j=O("chrome.storage.local.set")};function ra(a){var b;return H(function(c){if(1==c.g)return D(c,P.m(a),2);b=c.h;return c.return(b[a])})}function sa(){var a=null;a=void 0===a?{}:a;var b;return H(function(c){if(1==c.g)return D(c,ra("savedTab"),2);b=c.h;return c.return(b||a)})}function ta(a){var b=void 0;b=void 0===b?[]:b;var c;return H(function(d){if(1==d.g)return D(d,ra(a),2);c=d.h;return d.return(c||b)})}
function ua(a){var b=void 0===b?new Set:b;var c;return H(function(d){if(1==d.g)return D(d,ta(a),2);c=d.h;return d.return(c&&c.length?new Set(c):b)})}function Q(a,b){var c={};return P.j((c[a]=b,c))};var R=Promise.resolve();function S(){return H(function(a){R=R.then(va);return a.return(R)})}function va(){return H(function(a){return a.return(ua("activeTabs"))})}function wa(a){return H(function(b){R=R.then(function(){return Q("activeTabs",Array.from(a))});return b.return(R)})}function xa(){return P.g("activeTabs")}
function ya(a){var b,c;return H(function(d){if(1==d.g){b=a;if(b.data&&"object"===typeof b.data)switch(c=b.data,c.type){case "devtools-opened":case "devtools-closed":d.g=3;return;default:console.warn("Unknown message: "+c.type)}else console.warn("Unknown message type: "+b.data);d.g=0}else return 5!=d.g?d=D(d,za(c.type,c.tabId),5):(d.g=0,d=void 0),d})}
function za(a,b){var c;return H(function(d){if(1==d.g)return b?D(d,S(),2):d.return();c=d.h;switch(a){case "devtools-opened":c.add(b);break;case "devtools-closed":c.delete(b)}return D(d,wa(c),0)})}function Aa(a){var b;return H(function(c){if(1==c.g)return D(c,S(),2);b=c.h;return c.return(b.has(a))})};var Ba=new Set("gndmhdcefbhlchkhipcnnbkcmicncehk ifajfiofeifbbhbionejdliodenmecna imgmjcnolbhljlnimjbnmeokfljgjokj haldlgldplgnggkjaafhelgiaglafanh hjngolefdpdnooamgdldlkjgmdcmcjnc ckanlcmoklgdobgbkebohpficpiogcif kbohafcopfpigkjdimdcdgenlhkmhbnc hmfjajhcddnpmhkhakkgoibealjcffho kmffehbidlalibfeklaefnckpidbodff fabpdabkjmplhckhfhknoemeihjffobe mnehmlglkdbpcimikacjgegmpebacoab ajphlblkfpppdpkgokiejbjfohfohhmk inoeonmfapjbbkmdafoankkfajkcphgd ikfigngpioedjjooplekefdiilaokaik cffehcbbnlffijenmdjklfjggaighnld iheobagjkfklnlikgihanlhcddjoihkg mloajfnmjckfjbeeofcdaecbelnblden emmgndmggimgmmpciejhnkcnlillakfn unit-test:allowed-extension-id".split(" ")),
Ca=new Set(["unit-test:disallowed-extension-id"]),V;V=Promise.resolve();
function Da(){var a,b,c,d;return H(function(k){switch(k.g){case 1:return D(k,P.s(),2);case 2:return a=k.h,b=a.filter(Ea).map(function(m){return m.id}),c=new Set(b),D(k,Q("disabledExtensions",Array.from(c)),3);case 3:return d=b.map(function(m){var f;return H(function(e){if(1==e.g)return e.i=2,D(e,P.i(m,!1),4);2!=e.g?(e.g=0,e.i=0):(f=E(e),console.warn("Error disabling "+m+" ("+f+")"),c.delete(m),e.g=0)})}),D(k,Promise.all(d),4);case 4:return D(k,Q("disabledExtensions",Array.from(c)),0)}})}
function Ea(a){return a.enabled&&"extension"==a.type?Ca.has(a.id)?!0:"admin"==a.installType||Ba.has(a.id)?!1:!0:!1}function Fa(){return H(function(a){V=V.then(Da);return a.return(V)})}function Ga(){var a,b;return H(function(c){return 1==c.g?D(c,ua("disabledExtensions"),2):3!=c.g?(a=c.h,b=Array.from(a).map(function(d){return H(function(k){if(1==k.g)return D(k,P.i(d,!0),2);a.delete(d);k.g=0})}),D(c,Promise.all(b),3)):D(c,Q("disabledExtensions",Array.from(a)),0)})}function W(){return V=V.then(Ga)};function Ha(a){var b;return H(function(c){if(1==c.g)return D(c,P.A({discarded:!1}),2);b=c.h;return c.return(Promise.all(b.filter(function(d){return d.id!=a}).map(function(d){return P.o(d.id)})))})};function X(){var a;return H(function(b){if(1==b.g)return D(b,sa(),2);a=b.h;return b.return(a)})}Promise.resolve();
function Ia(a){var b,c;return H(function(d){switch(d.g){case 1:return D(d,Aa(a.id),2);case 2:if(b=d.h)throw console.warn("Devtools detected in tab "+a.id),new oa;d.i=3;return D(d,P.createWindow({type:"popup",state:"locked-fullscreen",tabId:a.id,incognito:a.incognito}),5);case 5:var k={};k=P.j((k.savedTab=a,k));return D(d,k,6);case 6:return D(d,Promise.all([Ha(a.id),Fa()]),7);case 7:d.g=4;d.i=0;break;case 3:return c=E(d),D(d,Y(a),8);case 8:throw c;case 4:return P.B(a.id),D(d,Ja(),9);case 9:return d.return(new J(!0))}})}
function Ka(a){return H(function(b){return 1==b.g?D(b,P.createWindow({type:"normal",state:"locked-fullscreen",url:a}),2):3!=b.g?D(b,Fa(),3):b.return(new J(!0))})}function La(a){var b;return H(function(c){if(1==c.g)return D(c,X(),2);if(3!=c.g){b=c.h;if(null==b||b.id!=a.id)throw new na;return D(c,Y(b),3)}return c.return(new J(!1))})}
function Ma(){var a;return H(function(b){switch(b.g){case 1:return D(b,P.h(),2);case 2:a=b.h;if(null==a)throw new qa;return D(b,P.l(a.id,{state:"normal"}),3);case 3:return D(b,W(),4);case 4:return b.return(new J(!1))}})}function Y(a){return H(function(b){if(1==b.g)return D(b,P.g("savedTab"),2);if(3!=b.g)return D(b,Promise.all([W(),Na(a)]),3);chrome.webNavigation.onCommitted.hasListener(Z)&&chrome.webNavigation.onCommitted.removeListener(Z);b.g=0})}
function Na(a){var b,c;return H(function(d){switch(d.g){case 1:return D(d,P.h(),2);case 2:return b=d.h,D(d,P.l(b.id,{state:"fullscreen"}),3);case 3:return d.i=4,D(d,P.D(a.windowId),6);case 6:d.g=5;d.i=0;break;case 4:return E(d),D(d,P.createWindow({type:"normal",state:"normal",tabId:a.id,incognito:a.incognito}),7);case 7:return d.return();case 5:return D(d,P.v(a.id,{index:a.index,windowId:a.windowId}),8);case 8:return c=d.h,D(d,P.C(c.id,{active:!0}),9);case 9:if(null!=a.groupId&&0<=a.groupId)return D(d,
P.F({groupId:a.groupId,tabIds:c.id}),0);d.g=0}})}function Oa(a){var b;return H(function(c){if(1==c.g)return D(c,Pa(a),2);b=c.h;return c.return(new J(b))})}function Pa(a){var b;return H(function(c){if(1==c.g)return D(c,X(),2);b=c.h;return c.return(!!b&&b.id==a.id)})}
function Z(a){var b;return H(function(c){if(1==c.g)return 0!==a.frameId?c.return():D(c,X(),2);b=c.h;if(!b)return console.warn("The navigation listener was installed without a locked tab."),c.return();if(b.id!=a.tabId)return console.log("A navigation to "+a.url+" occurred in tab "+a.tabId+", which is not the locked tab."),c.return();if(Qa(a.url))return c.return();console.warn("An unauthorized navigation to "+a.url+" occurred in tab "+a.tabId);return D(c,Y(b),0)})}
function Ja(){var a;return H(function(b){if(1==b.g)return D(b,X(),2);a=b.h;if(!a)return b.return();chrome.webNavigation.onCommitted.hasListener(Z)||chrome.webNavigation.onCommitted.addListener(Z);b.g=0})}function Qa(a){return(chrome.runtime.getManifest().externally_connectable.matches||[]).map(function(b){b=new URLPattern(b);return new URLPattern({hostname:b.hostname,pathname:b.pathname,protocol:b.protocol})}).some(function(b){return b.test(a)})};function Ra(a,b,c){try{console.log("Extension "+chrome.runtime.id+" received request: '"+a.command+"' from sender with id "+b);switch(a.command){case "lockWindow":var d=Ka(a.urls);break;case "unlockCurrentWindow":d=Ma();break;default:throw new M;}d.then(function(k){console.log("Extension "+chrome.runtime.id+" returned response: "+JSON.stringify(k)+" to request: '"+a.command+"'");c(k)},function(k){return Sa(a,b,k,c)});return!0}catch(k){Sa(a,b,k,c)}}
function Ta(a,b,c){try{console.log("Extension "+chrome.runtime.id+" received request: '"+a.command+"' from tab "+b.id+" with url "+b.url);switch(a.command){case "lock":var d=Ia(b);break;case "isLocked":d=Oa(b);break;case "unlock":d=La(b);break;default:throw new M;}d.then(function(k){console.log("Extension "+chrome.runtime.id+" returned response: "+JSON.stringify(k)+" to request: '"+a.command+"'");c(k)},function(k){return Ua(a,b.id,b.url,k,c)});return!0}catch(k){Ua(a,b.id,b.url,k,c)}}
function Sa(a,b,c,d){c=c instanceof K?c:new N(c);console.error("Extension "+chrome.runtime.id+" returned error: '"+c+"' in response to request: '"+a.command+"' from sender with id "+b);d(c)}function Ua(a,b,c,d,k){d=d instanceof K?d:new N(d);console.error("Extension "+chrome.runtime.id+" returned error: '"+d+"' in response to request: '"+a.command+"' from tab "+b+" with url "+c);k(d)};H(function(a){chrome.runtime.onStartup.addListener(xa);chrome.tabs.onRemoved.addListener(function(b){var c;return H(function(d){if(1==d.g)return D(d,S(),2);c=d.h;c.delete(b);return D(d,wa(c),0)})});self.addEventListener("message",ya);a.g=0});chrome.runtime.onStartup.addListener(W);
H(function(a){chrome.tabs.onRemoved.addListener(function(b){var c;return H(function(d){if(1==d.g)return D(d,X(),2);if((c=d.h)&&c.id==b)return console.warn("Tab "+b+" was closed while locked"),D(d,Y(c),0);d.g=0})});return D(a,Ja(),0)});chrome.runtime.onMessageExternal.addListener(function(a,b,c){if(null!=b.tab)return Ta(a,b.tab,c);if(null!=b.id)return Ra(a,b.id,c)});console.log("Loaded extension "+chrome.runtime.id+", version "+chrome.runtime.getManifest().version+".");
